// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDESBKGkTir6PlfewBQfZT6EDiD-vFKNYo',
    appId: '1:288740335268:android:843fe7d69492bafff8d031',
    messagingSenderId: '288740335268',
    projectId: 'rm-emp',
    storageBucket: 'rm-emp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtbzin213pIPE92sL7VAXvWHxaw5HgU34',
    appId: '1:288740335268:ios:2c3060f54db09f83f8d031',
    messagingSenderId: '288740335268',
    projectId: 'rm-emp',
    storageBucket: 'rm-emp.firebasestorage.app',
    iosBundleId: 'com.rightminddev.rmemp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7t-KoyfGWh2JAv1fkqb9WUW1gxabWves',
    appId: '1:288740335268:web:d9b72d1e151ea512f8d031',
    messagingSenderId: '288740335268',
    projectId: 'rm-emp',
    authDomain: 'rm-emp.firebaseapp.com',
    storageBucket: 'rm-emp.firebasestorage.app',
    measurementId: 'G-9W4RQPEYMZ',
  );

}