// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX4Km5u52z48hKBahoNg8Rt0iAhDPyJQs',
    appId: '1:436937858575:web:079f8d03ec72251bd5cd7a',
    messagingSenderId: '436937858575',
    projectId: 'rm-test-a6159',
    authDomain: 'rm-test-a6159.firebaseapp.com',
    storageBucket: 'rm-test-a6159.firebasestorage.app',
    measurementId: 'G-Q0B60CV1F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPkXh5qNh3djz1r-51p_ir3q2RGA0XpMc',
    appId: '1:436937858575:android:a966a5daa12bff60d5cd7a',
    messagingSenderId: '436937858575',
    projectId: 'rm-test-a6159',
    storageBucket: 'rm-test-a6159.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqFUZX3Iqxkmuse-BSPI1FWsrR4HvwFaU',
    appId: '1:436937858575:ios:6b6ae28d2f7f1ebfd5cd7a',
    messagingSenderId: '436937858575',
    projectId: 'rm-test-a6159',
    storageBucket: 'rm-test-a6159.firebasestorage.app',
    iosBundleId: 'com.rightmindtest.rmtest',
  );
}
